name: Deploy DotNet project to Azure Function App

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

env:
  AZURE_FUNCTIONAPP_NAME: 'flightfinder-api'
  DOTNET_VERSION: '9.0.x'
  # Explicit project file path provided by user
  PROJECT_FILE: './FlightFinder.API.csproj'
  PUBLISH_OUTPUT: './output'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Show repo layout (diagnostic - optional; remove after confirming path)
        shell: pwsh
        run: |
          Write-Host "Repository root contents:"
          Get-ChildItem -Force
          Write-Host "Searching for csproj files (first 50):"
          Get-ChildItem -Path . -Recurse -Filter *.csproj | Select-Object -ExpandProperty FullName -First 50

      - name: Publish Function Project
        shell: pwsh
        run: |
          Write-Host "Publishing project: ${{ env.PROJECT_FILE }}"
          dotnet publish ${{ env.PROJECT_FILE }} -c Release -o ${{ env.PUBLISH_OUTPUT }}

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.PUBLISH_OUTPUT }}'
