# Deploy a .NET Function App using Azure RBAC (AZURE_RBAC_CREDENTIALS secret)
name: Deploy DotNet project to Azure Function App

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

env:
  AZURE_FUNCTIONAPP_NAME: 'flightfinder-api'             # set to the exact app name you created
  AZURE_FUNCTIONAPP_PROJECT_PATH: './src/FlightFinder.API' # change to folder containing your Function .csproj
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Publish Function Project
      shell: pwsh
      run: |
        pushd ${{ env.AZURE_FUNCTIONAPP_PROJECT_PATH }}
        dotnet publish -c Release -o ./output
        popd

    - name: Run Azure Functions Action
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PROJECT_PATH }}/output'
